name: dr_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  fancy_on_boarding: ^1.8.0-nullsafety.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/